apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlPVC
  namespace: notesapp
  labels:
    app: mysqlPVC
spec:
  storageClassName: gp3
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi