apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: notesapp
type: Opaque
data:
  DB_USER: "prem"
  DB_PASSWORD: "VGVzdEAxMjM=" #Test@123
  MYSQL_ROOT_PASSWORD: "VGVzdEAxMjM=" #Test@123