apiVersion: v1
kind: Service
metadata:
  name: appservice
  namespace: notesapp
spec:
  selector:
    app: notesapp
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000 

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: notesapp
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306