apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notesappCD
  namespace: argocd
  project: default
  source:
    repoURL: https://github.com/<your-username>/cloudnotes-eks-argocd.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: notesapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true